Controllers/TimetableController.cs
using College.Domain;
using College.Domain.Entities;
using College.Infrastructure;
using College.Models;
using Microsoft.AspNetCore.Mvc;

namespace College.Controllers
{
    public class TimetableController : Controller
    {
        private readonly DataManager _dataManager;
        public TimetableController(DataManager dataManager)
        {
            _dataManager = dataManager;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Timetable> list = await _dataManager.Timetables.GetTimetableAsync();
            IEnumerable<TimetableDTO> listDTO = HelperDTO.TransformTimetables(list);
            return View(listDTO);
        }
        public async Task<IActionResult> ScheduleShow()
        {
            IEnumerable<Timetable> list = await _dataManager.Timetables.GetTimetableAsync();
            IEnumerable<TimetableDTO> listDTO = HelperDTO.TransformTimetables(list);
            return View(listDTO);
        }
        public async Task<IActionResult> ChangesShow()
        {
            IEnumerable<Timetable> list = await _dataManager.Timetables.GetTimetableAsync();
            IEnumerable<TimetableDTO> listDTO = HelperDTO.TransformTimetables(list);
            return View(listDTO);
        }
    }
}

Views/Timetable/ChangesShow.cshtml
@model IEnumerable<TimetableDTO>
@{
    string strTitle = "Заміни";
    ViewBag.Title = strTitle;
}
<div class="col-8 col-12-medium imp-medium">
    <div id="content">
        @if (Model.Any())
        {
            <section class="box article-list">
                <h2 class="icon fa-file-alt">
                    @strTitle
                </h2>
                @foreach (TimetableDTO entity in Model)
                {
                    <article class="box excerpt major">

                        <a asp-area="" asp-controller="Timetable" asp-action="" asp-route-id="@entity.Id">
                            <img style="height:300px; width:auto;" src="~/img/@entity.Changes" alt="" />
                        </a>
                    </article>
                }
            </section>
        }
        else
        {
            <h3>Записи відсутні</h3>
        }
    </div>
</div>

Views/Timetable/Index.cshtml
@model IEnumerable<TimetableDTO>
@{
    string strTitle = "Розклад";
    ViewBag.Title = strTitle;
}
<div class="col-8 col-12-medium imp-medium">
    <div id="content">
        @if (Model.Any())
        {
            <section class="box article-list">
                <h2 class="icon fa-file-alt">
                    @strTitle
                </h2>
                <h3 class ="icon fa-file-alt">
                    Розклади
                </h3>
                @foreach (TimetableDTO entity in Model)
                {
                    <article class="box excerpt major">

                        <a asp-area="" asp-controller="Timetable" asp-action="" asp-route-id="@entity.Id">
                            <img style="height:300px; width:auto;" src="~/img/@entity.Schedule" alt="" />
                        </a>
                    </article>
                }
                <h3 class ="icon fa-file-alt">
                    Заміни
                </h3>
                @foreach (TimetableDTO entity in Model)
                {
                    <article class="box excerpt major">

                        <a asp-area="" asp-controller="Timetable" asp-action="" asp-route-id="@entity.Id">
                            <img style="height:300px; width:auto;" src="~/img/@entity.Changes" alt="" />
                        </a>
                    </article>
                }
            </section>
        }
        else
        {
            <h3>Записи відсутні</h3>
        }
    </div>
</div>

Views/Timetable/ScheduleShow.cshtml
@model IEnumerable<TimetableDTO>
@{
    string strTitle = "Розклади";
    ViewBag.Title = strTitle;
}
<div class="col-8 col-12-medium imp-medium">
    <div id="content">
        @if (Model.Any())
        {
            <section class="box article-list">
                <h2 class="icon fa-file-alt">
                    @strTitle
                </h2>
                @foreach (TimetableDTO entity in Model)
                {
                    <article class="box excerpt major">

                        <a asp-area="" asp-controller="Timetable" asp-action="" asp-route-id="@entity.Id">
                            <img style="height:300px; width:auto;" src="~/img/@entity.Schedule" alt="" />
                        </a>
                    </article>
                }
            </section>
        }
        else
        {
            <h3>Записи відсутні</h3>
        }
    </div>
</div>